import { getManifest } from 'tailmantic/collector';
import './accordion.styles.js';
import './alert.styles.js';
import './app-bar.styles.js';
import './avatar.styles.js';
import './badge.styles.js';
import './bottom-navigation.styles.js';
import './breadcrumbs.styles.js';
import './button-group.styles.js';
import './button.styles.js';
import './card.styles.js';
import './checkbox.styles.js';
import './chip.styles.js';
import './dialog.styles.js';
import './divider.styles.js';
import './drawer.styles.js';
import './floating-action-button.styles.js';
import './icon-button.styles.js';
import './icon-glyph.styles.js';
import './link.styles.js';
import './list.styles.js';
import './menu.styles.js';
import './tokens.styles.js';
import './app.styles.js';
import './pages.styles.js';

export default getManifest();
