import { register } from 'tailmantic/collector';

register.all({
  ':root': {
    '--c-brand':        '#d6533d',
    '--c-brand-hover':  '#bb432f',
    '--c-brand-light':  '#fff0e9',
    '--c-brand-ring':   'rgba(214,83,61,.24)',
    '--c-bg':           '#f3f5f0',
    '--c-surface':      '#ffffff',
    '--c-border':       '#dfe5dd',
    '--c-border-focus': '#d6533d',
    '--c-text':         '#202a25',
    '--c-text-muted':   '#63716a',
    '--c-text-light':   '#8d9992',
    '--c-success':      '#287451',
    '--c-success-bg':   '#e8f4ec',
    '--c-warning':      '#a96b16',
    '--c-warning-bg':   '#fbf1dc',
    '--c-danger':       '#bd453d',
    '--c-danger-bg':    '#fbecea',
    '--c-info':         '#36747b',
    '--c-info-bg':      '#e8f2f1',
    '--c-sidebar':      '#20312b',
    '--c-sidebar-border':'#34463f',
    '--c-sidebar-text': '#dce5df',
    '--c-sidebar-muted':'#9aa9a0',
    '--shadow-sm':      '0 2px 8px rgba(32,42,37,.05)',
    '--shadow-md':      '0 8px 22px rgba(32,42,37,.10)',
    '--shadow-lg':      '0 18px 48px rgba(20,32,26,.18)',
    '--radius-sm':      '5px',
    '--radius-md':      '8px',
    '--radius-lg':      '10px',
    '--radius-xl':      '12px',
    '--radius-full':    '9999px',
  },
  '*': {
    'box-sizing': 'border-box',
    margin: '0',
    padding: '0',
    '@media (prefers-reduced-motion: reduce)': {
      'scroll-behavior': 'auto',
      'animation-duration': '0.01ms',
      'animation-iteration-count': '1',
      'transition-duration': '0.01ms',
    },
  },
  'body': {
    tw: ['antialiased font-[DM_Sans,sans-serif] text-sm leading-[1.6]', 'text-[var(--c-text)] bg-[var(--c-bg)]'],
  },
  '::selection': { color: '#fff', 'background-color': 'var(--c-brand)' },
});
